services:
  cypherbench-company:
    container_name: cypherbench-company
    image: megagonlabs/neo4j-with-loader:2.4
    volumes:
      - ../benchmark/graphs/simplekg/company_simplekg.json:/init/graph.json
    ports:
      - 15062:7687
    environment:
      NEO4J_AUTH: $NEO4J_USERNAME/$NEO4J_PASSWORD
      NEO4J_server_http__enabled__modules: "TRANSACTIONAL_ENDPOINTS,UNMANAGED_EXTENSIONS,ENTERPRISE_MANAGEMENT_ENDPOINTS"
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'

  cypherbench-fictional-character:
    container_name: cypherbench-fictional-character
    image: megagonlabs/neo4j-with-loader:2.4
    volumes:
      - ../benchmark/graphs/simplekg/fictional_character_simplekg.json:/init/graph.json
    ports:
      - 15063:7687
    environment:
      NEO4J_AUTH: $NEO4J_USERNAME/$NEO4J_PASSWORD
      NEO4J_server_http__enabled__modules: "TRANSACTIONAL_ENDPOINTS,UNMANAGED_EXTENSIONS,ENTERPRISE_MANAGEMENT_ENDPOINTS"
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'

  cypherbench-flight-accident:
    container_name: cypherbench-flight-accident
    image: megagonlabs/neo4j-with-loader:2.4
    volumes:
      - ../benchmark/graphs/simplekg/flight_accident_simplekg.json:/init/graph.json
    ports:
      - 15064:7687
    environment:
      NEO4J_AUTH: $NEO4J_USERNAME/$NEO4J_PASSWORD
      NEO4J_server_http__enabled__modules: "TRANSACTIONAL_ENDPOINTS,UNMANAGED_EXTENSIONS,ENTERPRISE_MANAGEMENT_ENDPOINTS"
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'

  cypherbench-geography:
    container_name: cypherbench-geography
    image: megagonlabs/neo4j-with-loader:2.4
    volumes:
      - ../benchmark/graphs/simplekg/geography_simplekg.json:/init/graph.json
    ports:
      - 15065:7687
    environment:
      NEO4J_AUTH: $NEO4J_USERNAME/$NEO4J_PASSWORD
      NEO4J_server_http__enabled__modules: "TRANSACTIONAL_ENDPOINTS,UNMANAGED_EXTENSIONS,ENTERPRISE_MANAGEMENT_ENDPOINTS"
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'

  cypherbench-movie:
    container_name: cypherbench-movie
    image: megagonlabs/neo4j-with-loader:2.4
    volumes:
      - ../benchmark/graphs/simplekg/movie_simplekg.json:/init/graph.json
    ports:
      - 15066:7687
    environment:
      NEO4J_AUTH: $NEO4J_USERNAME/$NEO4J_PASSWORD
      NEO4J_server_http__enabled__modules: "TRANSACTIONAL_ENDPOINTS,UNMANAGED_EXTENSIONS,ENTERPRISE_MANAGEMENT_ENDPOINTS"
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'

  cypherbench-nba:
    container_name: cypherbench-nba
    image: megagonlabs/neo4j-with-loader:2.4
    volumes:
      - ../benchmark/graphs/simplekg/nba_simplekg.json:/init/graph.json
    ports:
      - 15067:7687
    environment:
      NEO4J_AUTH: $NEO4J_USERNAME/$NEO4J_PASSWORD
      NEO4J_server_http__enabled__modules: "TRANSACTIONAL_ENDPOINTS,UNMANAGED_EXTENSIONS,ENTERPRISE_MANAGEMENT_ENDPOINTS"
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'

  cypherbench-politics:
    container_name: cypherbench-politics
    image: megagonlabs/neo4j-with-loader:2.4
    volumes:
      - ../benchmark/graphs/simplekg/politics_simplekg.json:/init/graph.json
    ports:
      - 15068:7687
    environment:
      NEO4J_AUTH: $NEO4J_USERNAME/$NEO4J_PASSWORD
      NEO4J_server_http__enabled__modules: "TRANSACTIONAL_ENDPOINTS,UNMANAGED_EXTENSIONS,ENTERPRISE_MANAGEMENT_ENDPOINTS"
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
